# Jekyll Resume Theme

# Site settings
title: Alice Weigt
email: almw@protonmail.com
description: CV for Alice Weigt
baseurl: ""
url: "http://alicegrey.github.io"
name: Alice Weigt
job: hacker
location: Bay Area, California
languages: C++, Java, and Python
github_username:  alicegrey
linkedin_username: AliceWeigt
email_address: almw@protonmail

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
