# Jekyll Resume Theme

# Site settings
title: Jekyll Resume
email: almw@protonmail.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "http://mattcouchman.co.uk/jekyll-resume"
name: Alice Weigt
job: front end engineer
location: Birmingham, UK
languages: HTML, CSS and Javascript
github_username:  alicegrey
email_address: almw@protonmail

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal